#### When I discovered PyCaret, I wanted to test it on the older version of this project to see if it produced similar results

In [5]:
import pandas as pd
import os 
os.chdir(r'C:\Users\galla\OneDrive\Documents\Test')

In [6]:
train = pd.read_csv('heart_failure_clinical_records_dataset_train.csv')
test = pd.read_csv('heart_failure_clinical_records_dataset_test.csv')

In [10]:
train.shape

(239, 13)

In [9]:
test.shape

(60, 12)

In [11]:
train.isna().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [12]:
test.isna().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
dtype: int64

# PyCaret Model

In [13]:
from pycaret.classification import *
s = setup(train, target = 'DEATH_EVENT', session_id = 123)

# Compare Models

In [14]:
# functional API
best = compare_models()

# OOP API
best = s.compare_models()

In [15]:
print(best)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# Analyze Model

In [16]:
# functional API
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [17]:
# OOP API
s.evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

# Make Predictions

In [21]:
predictions = predict_model(best, data = test)
predictions.head(10)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,prediction_label,prediction_score
0,68,1,1021,1,35,0,271000.00000,1.10,134,1,0,197,0,0.9200
1,55,0,582,1,35,1,371000.00000,0.70,140,0,0,197,0,0.9318
2,73,0,582,0,20,0,263358.03125,1.83,134,1,0,198,0,0.9149
3,65,0,118,0,50,0,194000.00000,1.10,145,1,1,200,0,0.9189
4,42,1,86,0,35,0,365000.00000,1.10,139,1,1,201,0,0.9444
5,47,0,582,0,25,0,130000.00000,0.80,134,1,0,201,0,0.9310
6,58,0,582,1,25,0,504000.00000,1.00,138,1,0,205,0,0.9448
7,75,0,675,1,60,0,265000.00000,1.40,125,0,0,205,0,0.9340
8,58,1,57,0,25,0,189000.00000,1.30,132,1,1,205,0,0.9332
9,55,1,2794,0,35,1,141000.00000,1.00,140,1,0,206,0,0.9298

In [22]:
predictions[predictions['prediction_score'] < .9]

Empty DataFrame
Columns: [age, anaemia, creatinine_phosphokinase, diabetes, ejection_fraction, high_blood_pressure, platelets, serum_creatinine, serum_sodium, sex, smoking, time, prediction_label, prediction_score]
Index: []

#### From the above data frame of predictions, I saw that the prediction score for each test was above .9 which was a slight improvement over my last model. I learned that this model can help produce better results because of human error in the previous project and PyCaret can allow me to do this with much less code